### PR TITLE
Added lib to NPM and created the main file attr in the package.json

### PR DESCRIPTION
**Pull request by qrpike**

### CODE REVIEW

**Comment by Joelkang** [comment]
+1 for getting this into NPM

**Comment by screeley** [comment]
@qrpike any chance I could get the ability to publish to player.js on NPM?

**Comment by qrpike** [comment]
Sure, what's your npm name/email. Thanks.

**Comment by screeley** [comment]
screeley/sean@embed.ly

On Fri, Jul 24, 2015 at 1:23 PM, Quinton Pike <notifications@github.com>
wrote:

> Sure, what's your npm name/email. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embedly/player.js/pull/23#issuecomment-124585706>.
>



-- 
Sean Creeley | Co-Founder Embedly
100 North Washington St #503 | Boston 02114
415.891.9917 | sean@embed.ly | @screeley
http://embed.ly | @embedly

**Comment by qrpike** [comment]
Cool - added you as owner.

**Comment by screeley** [comment]
Thanks!

On Friday, July 24, 2015, Quinton Pike <notifications@github.com> wrote:

> Cool - added you as owner.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/embedly/player.js/pull/23#issuecomment-124587444>.
>


-- 
Sean Creeley | Co-Founder Embedly
100 North Washington St #503 | Boston 02114
415.891.9917 | sean@embed.ly | @screeley
http://embed.ly | @embedly

**Pull request merged**
